### PR TITLE
repair typo in devel section

### PR DESCRIPTION
**Pull request by mimi1vx**
in line : 'Requires: %{name} = %{version}-%{release}'  must must be space between } and =

### CODE REVIEW

**Comment by juhp** [comment]
(I added a comment to your commit - I don't think this is a right change.)

**Comment by mimi1vx** [comment]
@juhp (+-+) is what? and no , i hit missing space between `%{name}` and `=` , i tested fix, is working

**Comment by mimi1vx** [comment]
@juhp Ahh,

you mean : 
`(+-+) :: String -> String -> String
"" +-+ s = s
s +-+ "" = s
s +-+ t = s ++ " " ++ t`


ahh `isa` in SUSE is `""` ==> `"%{name}") ++ isa +-+ " = %{version}-%{release}"`  = `%{name}= %{ver...` which is buggy

**Comment by mimi1vx** [comment]
@juhp or my coleguage Jan Matejka propose this fix : 

`putHdr "Requires" $ ((if binlib then "ghc-%{name}" else "%{name}") ++ isa) +-+ "= %{version}-%{release}"`

**Comment by juhp** [comment]
That makes sense - I wonder if it is better to change the associativity of +-+ though.

**Comment by juhp** [comment]
Could you see if:

```haskell
diff --git a/src/SysCmd.hs b/src/SysCmd.hs
index 6214cb6..f81795f 100644
--- a/src/SysCmd.hs
+++ b/src/SysCmd.hs
@@ -115,6 +115,7 @@ removeTrailingNewline str =
   then init str
   else str
 
+infixr 5 +-+
 (+-+) :: String -> String -> String
 "" +-+ s = s
 s +-+ "" = s
```

works as well as the change Jan suggested?

**Comment by juhp** [comment]
`infixr 4 +-+` looks okay to me.

**Comment by mimi1vx** [comment]
@juhp `infixr 4 +-+` works good

**Comment by juhp** [comment]
Cool thanks - I will push that soon, and then close this.

Thank you for catching and reporting this bug.

**Comment by juhp** [comment]
commit b682057 has the change

**Comment by mimi1vx** [comment]
please commit to hackage:)

**Pull request closed without merging**
