### PR TITLE
Build with Cabal-3.2.0.0

### LINKED ISSUE #63: Build with Cabal-3.2.0
In [19e2a02b924](https://github.com/juhp/cabal-rpm/commit/19e2a02b92448b0bb1b8aa6bbdc75cd3ac9e0a24), Cabal ≥ 3.2.0 was forbidden, even though the fix is simple:

```patch
--- Commands/Spec.hs.orig
+++ Commands/Spec.hs
@@ -27,28 +27,26 @@
 import Header (headerOption, withSpecHead)
 import PackageUtils (bringTarball, latestPackage, PackageData (..), prepare)
 import SimpleCabal (buildable, mkPackageName, PackageDescription (..),
                     PackageIdentifier(..), PackageName, showVersion)
 import SimpleCmd ((+-+), grep_, removePrefix)
 import Stackage (defaultLTS)
-import Types
+import Types (Flags, LibPkgType(Base, Devel, Doc, Prof, Static),
+              PackageType(BinaryPkg, SpecFile, StandalonePkg),
+              PackageVersionSpecifier(PVPackageId), pvsStream,
+              RpmPackage(RpmHsLib), showRpm, showStream, Stream)
 
 import Control.Monad    (filterM, forM_, unless, void, when, (>=>))
 
-#if (defined(MIN_VERSION_base) && MIN_VERSION_base(4,8,0))
-#else
---import Control.Applicative ((<$>))
-#endif
-
 import Data.Char        (toUpper)
 import Data.List        (groupBy, intercalate, intersect, isPrefixOf,
                          nub, sort, (\\))
 import Data.Maybe       (isJust, fromMaybe, fromJust)
 import Data.Time.Clock  (getCurrentTime)
 import Data.Time.Format (formatTime)
-import qualified Data.Version as V
+import qualified Data.Version as V (showVersion)
 
 import Distribution.Text (display)
 import Distribution.License  (License (..)
 #if defined(MIN_VERSION_Cabal) && MIN_VERSION_Cabal(2,2,0)
                              , licenseFromSPDX
 #endif
@@ -77,12 +75,14 @@
 import System.Locale (defaultTimeLocale)
 #endif
 import System.FilePath (takeBaseName, (</>), (<.>))
 
 import qualified Paths_cabal_rpm (version)
 
+import qualified Distribution.Utils.ShortText as ST (fromShortText)
 
 rstrip :: (Char -> Bool) -> String -> String
 rstrip p = reverse . dropWhile p . reverse
 
 #if defined(MIN_VERSION_Cabal) && MIN_VERSION_Cabal(2,0,0)
 #else
@@ -179,25 +179,25 @@
   put $ "# generated by cabal-rpm-" ++ V.showVersion Paths_cabal_rpm.version
     +-+ unwords (["--standalone" | standalone] ++ ["--stream " ++ showStream (fromJust mstream) | isJust mstream, mstream /= Just defaultLTS] ++ ["--subpackage" | subpackage])
   put "# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/"
   putNewline
 
   -- Some packages conflate the synopsis and description fields.  Ugh.
-  let syn = synopsis pkgDesc
+  let syn = ST.fromShortText $ synopsis pkgDesc
   when (null syn) $
     warn verbose "this package has no synopsis."
   let initialCapital (c:cs) = toUpper c:cs
       initialCapital [] = []
   let syn' = if null syn
              then "Haskell" +-+ name +-+ "package"
              else (unwords . lines . initialCapital) syn
   let summary = rstrip (== '.') syn'
   when (length ("Summary     : " ++ syn') > 79) $
     warn verbose "this package has a long synopsis."
 
-  let descr = description pkgDesc
+  let descr = ST.fromShortText $ description pkgDesc
   when (null descr) $
     warn verbose "this package has no description."
   let descLines = (formatParagraphs . initialCapital . filterSymbols . finalPeriod) $ if null descr then syn' else descr
       finalPeriod cs = if last cs == '.' then cs else cs ++ "."
       filterSymbols (c:cs) =
         if c `notElem` "@\\" then c: filterSymbols cs
```

The above patch builds successfully on my system:

```bash
cabal-rpm --version
#2.0.5

ghc --numeric-version
#8.10.1
```

Moreover, to avoid a warning on GHC ≥ 8.10.1, the patch below could be applied:

```patch
--- Types.hs.orig
+++ Types.hs
@@ -29,13 +29,13 @@
   streamPkgToPVS,
   unversionedPkgId,
   Verbose(..)
   ) where
 
 import Data.Char (isDigit {--, toLower--})
-import Data.List
+import Data.List (groupBy, isPrefixOf, stripPrefix)
 import Data.Maybe (fromMaybe)
 #if (defined(MIN_VERSION_base) && MIN_VERSION_base(4,11,0))
 #else
 import Data.Semigroup ((<>))
 #endif
 import Distribution.Text (display)
```

### PR DESCRIPTION
**Pull request by hekkaidekapus**
Fixes #63.

### CODE REVIEW

**Comment by juhp** [comment]
I see I should have checked more carefully: unfortunately this breaks all builds with ghc < 8.10.

See https://travis-ci.org/github/juhp/cabal-rpm/builds/683005993

**Comment by juhp** [comment]
The simplest would probably be to handle this with CPP or a wrapper function perhaps.

**Comment by hekkaidekapus** [comment]
The problem lies in the travis file, at [this line](https://github.com/juhp/cabal-rpm/blob/0dc395e996bb89918e880603cff1451ef3f9c909/.travis.yml#L3): `cabal: 2.4`. That version does not build with GHC-8.10.1 as witnessed in [the build matrix](https://matrix.hackage.haskell.org/#/package/Cabal).

See also [this issue](https://github.com/haskell-CI/haskell-ci/issues/357) saying that _GHC 8.10.1 should use cabal-install-3.2 or later_.

Would you mind trying to use Cabal-3.2.0.0 in the CI? That should not be an issue for old GHCs because that release is backward-compatible down to GHC v-7.6.3, the lowest you also require in the CI configuration. Be aware that for cabal-install-3.2.0.0, you will probably have to [ditch](https://matrix.hackage.haskell.org/#/package/cabal-install) GHC-`{7.6.3, 7.8.4}`.

**Comment by juhp** [comment]
Okay thanks again, I went ahead and merged this.
After adding a little CPP I think everything is okay.
Maybe you can check HEAD works okay for you now?

**Comment by hekkaidekapus** [comment]
Thank you, too!
I just tried and the build succeeds now. One small warning remains, but that is okay. I paste it below for future reference, it was also mentioned in the original issue.

```text
src/Types.hs:35:8-16: warning: [-Wcompat-unqualified-imports]
    To ensure compatibility with future core libraries changes
    imports to Data.List should be
    either qualified or have an explicit import list.
```

**Pull request merged**
