### PR TITLE
SUSE doesn't have %licence macro

### PR DESCRIPTION
**Pull request by mimi1vx**
add if distro in files section to choose right macro for LICENSE files

### CODE REVIEW

**Comment by juhp** [comment]
Thanks - I did this slightly differently in cfd0536 : hope it works for you.

If you're keen to have a bugfix release - I can push another one.

**Comment by juhp** [comment]
Hmm but maybe you prefer not to define %license here for SUSE?

**Comment by mimi1vx** [comment]
I prefer not to define %license , in OBS we have automated tests for license

**Comment by juhp** [comment]
Okay I can't reopen - I'll try to remember - but good if you can open an issue to track this.

**Pull request closed without merging**
